#debug: true

server:
  port: ${PORT:8080}

#management:
#  endpoints:
#    web:
#      exposure.include: '*'

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/benwilcock/spring-petclinic-microservices-config